### ISSUE TITLE
Creates a blank file when in an HTML doc

### ISSUE THREAD

**Issue by DeathCheese763** [geekpradd/sublime-html5-minifier#1]
I am using Sublime text 3 on an OS X. works well with CSS files, so I don't know what the problem could be. please fix this program is a great idea I would love to use it.

**Comment by formspiel** [comment]
Same! I tried to minify a HTML file on OS X 10.10.1 w/ Sublime 3 --> blank file

**Comment by Konc** [comment]
I get a blank .min.css file with Sublime Text 3 on Windows 7 (64-bit).

**Comment by geekpradd** [comment]
Ok guys, I'll rewrite this from scratch

**Comment by geekpradd** [comment]
Thanks for the support, I thought no one was using my plugin.. 
I'll rewrite and the new version should be up tomorrow..
I'm not facing problems on Windows 8.1 but there is a saving error.

**Comment by geekpradd** [comment]
Guys, I think I found your problems.. the modules that I am using have some problems.. I'll use different modules

**Comment by geekpradd** [comment]
I've rewritten the code. If you are still facing problems, open another thread. Problem's gone on my system(s).
